export const LOGIN_USER = "LOGIN_USER";
export const SAVE_SENDER_COMPANY = "SAVE_SENDER_COMPANY";
export const GET_SENDER_COMPANY = "GET_SENDER_COMPANY";
export const UPDATE_SENDER_COMPANY = "UPDATE_SENDER_COMPANY";

export const GET_CLIENTS = "GET_CLIENTS";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const SAVE_CLIENT = "SAVE_CLIENT";
export const GET_CLIENT = "GET_CLIENT";
export const UPDATE_CLIENT = "UPDATE_CLIENT";
// FOR COURSES
export const GET_COURSES = "GET_COURSES";
export const DELETE_COURSE = "DELETE_COURSE";
export const SAVE_COURSE = "SAVE_COURSE";
export const GET_COURSE = "GET_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
// FOR STUDENTS
export const GET_STUDENTS = "GET_STUDENTS";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const SAVE_STUDENT = "SAVE_STUDENT";
export const GET_STUDENT = "GET_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";

export const ADD_INVOICE = "ADD_INVOICE";
export const GET_INVOICES = "GET_INVOICES";
export const DELETE_INVOICE = "DELETE_INVOICE";
export const GET_INVOICE = "GET_INVOICE";
export const UPDATE_INVOICE = "UPDATE_INVOICE";
export const DOWNLOAD_PDF = "DOWNLOAD_PDF";
export const MARK_PAYMENT_DONE = "MARK_PAYMENT_DONE";
